import mongoose from 'mongoose';

export interface ICard {
    id: string;
    oracle_id: string;
    multiverse_ids: number[];
    mtgo_id: number;
    tcgplayer_id: number;
    cardmarket_id: number;
    name: string;
    lang: string;
    released_at: string;
    uri: string;
    scryfall_uri: string;
    layout: string;
    highres_image: boolean;
    image_status: string;
    image_uris: {
        small: string;
        normal: string;
        large: string;
        png: string;
        art_crop: string;
        border_crop: string;
    };
    mana_cost: string;
    cmc: number;
    type_line: string;
    oracle_text: string;
    power: number;
    toughness: number;
    colors: string[];
    color_identity: string[];
    keywords: string[];
    legalities: {
        standard: string;
        future: string;
        historic: string;
        timeless: string;
        gladiator: string;
        pioneer: string;
        explorer: string;
        modern: string;
        legacy: string;
        pauper: string;
        vintage: string;
        penny: string;
        commander: string;
        oathbreaker: string;
        standardbrawl: string;
        brawl: string;
        alchemy: string;
        paupercommander: string;
        duel: string;
        oldschool: string;
        premodern: string;
        predh: string;
    };
    games: string[];
    reserved: boolean;
    game_changer: boolean;
    foil: boolean;
    nonfoil: boolean;
    finishes: string[];
    oversized: boolean;
    promo: boolean;
    reprint: boolean;
    variation: boolean;
    set_id: string;
    set: string;
    set_name: string;
    set_type: string;
    set_uri: string;
    set_search_uri: string;
    scryfall_set_uri: string;
    rulings_uri: string;
    prints_search_uri: string;
    collector_number: string;
    digital: boolean;
    rarity: string;
    card_back_id: string;
    game: string;
    price: number;
    artist: string;
    artist_ids: string[];
    illustration_id: string;
    border_color: string;
    frame: string;
    frame_effects: string[];
    security_stamp: string;
    full_art: boolean;
    textless: boolean;
    booster: boolean;
    story_spotlight: boolean;
    edhrec_rank: number;
    penny_rank: number;
    prices: {
        usd: number;
        usd_foil: number;
        usd_etched: number;
        eur: number;
        eur_foil: number;
        tix: number;
    };
    related_uris: {
        gatherer: string;
        tcgplayer_infinite_articles: string;
        tcgplayer_infinite_decks: string;
        edhrec: string;
    };
    purchase_uris: {
        tcgplayer: string;
        cardmarket: string;
        cardhoarder: string;
    };
    //TCGHub specific
    published: {
        tcgPlayer: boolean;
        cardmarket: boolean;
        lbc: boolean;
        ebay: boolean;
    }
}

const cardSchema = new mongoose.Schema({
    id: String,
    oracle_id: String,
    multiverse_ids: [Number],
    mtgo_id: Number,
    tcgplayer_id: Number,
    cardmarket_id: Number,
    name: String,
    lang: String,
    released_at: String,
    uri: String,
    scryfall_uri: String,
    layout: String,
    highres_image: Boolean,
    image_status: String,
    image_uris: {
        small: String,
        normal: String,
        large: String,
        png: String,
        art_crop: String,
        border_crop: String,
    },
    mana_cost: String,
    cmc: Number,
    type_line: String,
    oracle_text: String,
    power: Number,
    toughness: Number,
    colors: [String],
    color_identity: [String],
    keywords: [String],
    legalities: {
        standard: String,
        future: String,
        historic: String,
        timeless: String,
        gladiator: String,
        pioneer: String,
        explorer: String,
        modern: String,
        legacy: String,
        pauper: String,
        vintage: String,
        penny: String,
        commander: String,
        oathbreaker: String,
        standardbrawl: String,
        brawl: String,
        alchemy: String,
        paupercommander: String,
        duel: String,
        oldschool: String,
        premodern: String,
        predh: String,
    },
    games: [String],
    reserved: Boolean,
    game_changer: Boolean,
    foil: Boolean,
    nonfoil: Boolean,
    finishes: [String],
    oversized: Boolean,
    promo: Boolean,
    reprint: Boolean,
    variation: Boolean,
    set_id: String,
    set: String,
    set_name: String,
    set_type: String,
    set_uri: String,
    set_search_uri: String,
    scryfall_set_uri: String,
    rulings_uri: String,
    prints_search_uri: String,
    collector_number: String,
    digital: Boolean,
    rarity: String,
    card_back_id: String,
    artist: String,
    artist_ids: [String],
    illustration_id: String,
    border_color: String,
    frame: String,
    frame_effects: [String],
    security_stamp: String,
    full_art: Boolean,
    textless: Boolean,
    booster: Boolean,
    story_spotlight: Boolean,
    edhrec_rank: Number,
    penny_rank: Number,
    prices: {
        usd: Number,
        usd_foil: Number,
        usd_etched: Number,
        eur: Number,
        eur_foil: Number,
        tix: Number,
    },
    related_uris: {
        gatherer: String,
        tcgplayer_infinite_articles: String,
        tcgplayer_infinite_decks: String,
        edhrec: String,
    },
    purchase_uris: {
        tcgplayer: String,
        cardmarket: String,
        cardhoarder: String,
    },
    published: {
        tcgPlayer: Boolean,
        cardmarket: Boolean,
        lbc: Boolean,
        ebay: Boolean,
    },
    game: String,
    price: Number,
});

export const Card = mongoose.model('Card', cardSchema);
